train_data_dir: data/faq_wsd/train.json
val_data_dir: data/faq_wsd/val.json
model_name: csebuetnlp/banglabert
output_dir: output
num_sense: 3
max_seq_len: 96
batch_size: 4
lr: 0.00002
weight_decay: 0.01
epochs: 3
logging_step: 400
precision: fp16
warmup_ratio: 0.1
grad_clip: 1.0
pos: ALL
device: cuda
seed: 42
workers: 1
report_to: none
architecture: cosine
do_predict: false
